apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  name: APPSODY_PROJECT_NAME
  sidecar.istio.io/inject: "true"
  labels:
     app: APPSODY_PROJECT_NAME
     version: v1
spec:
  # Add fields here
  version: 1.0.0
  applicationImage: APPSODY_DOCKER_IMAGE 
  stack: APPSODY_STACK
  service:
    type: NodePort
    port: APPSODY_PORT
    annotations:
      prometheus.io/scrape: 'true'
  monitoring:
    labels:
      k8s-app: APPSODY_PROJECT_NAME
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /ready
      port: APPSODY_PORT
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /live
      port: APPSODY_PORT
    initialDelaySeconds: 5
    periodSeconds: 2
  expose: true
  envFrom:
  - configMapRef:
      name: jaeger-config

